machine:
  apache2:
    version: 2.4.27
  services:
    - docker

dependencies:
  post:
   - docker build -t install .

test:
  post:
   - docker run -p 8080:4001 install
   - curl -v http://localhost:4001

