machine:
  hosts:
    local.example.com: 127.0.0.1
  services:
    - docker

dependencies:
  post:
   - docker build -t install .

test:
  post:
   - docker run -p 8080:4001 install
   - curl -v http://localhost:4001

